### ISSUE TITLE
No such DSL method 'discordSend' found among steps

### ISSUE THREAD

**Issue by AnsisMalins** [jammehcow/jenkins-discord#15]
I tried to use the plugin in a pipeline script as shown in the example and got `No such DSL method 'discordSend' found among steps`.

It looks like the changes that add Pipeline support are newer than the latest release (1.1.0). Would you mind whipping up another release?

**Comment by jupjohn** [comment]
Will do that now.

**Comment by jupjohn** [comment]
Apologies for that taking so long. v1.2 has been pushed out.
