### ISSUE TITLE
Jenkins server

### ISSUE THREAD

**Issue by sgdc3** [jammehcow/jenkins-discord#17]
Just to let you know, i added your project to my public jenkins, if you want to host more jenkins job on it just send me an email at sgdc3.mail@gmail.com and i'll create an user for you to customize your build jobs ;) https://ci.codemc.org/view/jammehcow/

**Comment by jupjohn** [comment]
Thanks for that. I'm replacing my current server which will be more than capable to host an instance.

I appreciate the offer though.
