### ISSUE TITLE
[Resolved] Any way to alter the URL pushed to Discord Webhook?

### ISSUE THREAD

**Issue by CyberSecGuy** [jammehcow/jenkins-discord#26]
My jenkins is running internally on my LAN behind a proxy server that allows external access, however the Discord webhook sends my internal IP address as the domain for the artifacts, is there any way I can alter the URL displayed to reflect my web proxy?

https://i.imgur.com/glhD3Pk.png

Otherwise, I'll assume this is done via hostname? Or maybe something on the jenkins side.

**Comment by KocproZ** [comment]
You can set the jenkins location URL (that everything in jenkins uses) when you go from the main page to Manage Jenkins -> Configure System -> Jenkins location

**Comment by CyberSecGuy** [comment]
Thanks!
