### ISSUE TITLE
Obtaining .hpi file

### ISSUE THREAD

**Issue by raghuchinnannan** [jammehcow/jenkins-discord#27]
Hi, I'm new to Jenkins and I wanted to show build notifications in our Discord server and this plugin seems like a perfect option. But When I try to upload the plugin in the Advanced tab, it's asking for a .hpi file, could you please help about getting .hpi file for this plugin?

**Comment by KocproZ** [comment]
You can get .hpi file from [here](https://github.com/jammehcow/jenkins-discord/releases)

**Comment by raghuchinnannan** [comment]
Thanks for the quick response @KocproZ , it's really helpful. 

Could I also interest you in creating one more repo to send Amazon SNS notifications to Discord channels using Webhooks. Amazon SNS requires subscription confirmation before posting the data, so could you create some interface between Amazon SNS and Discord webhook, which Subscribes to the SNS topic and then convert the posted data to the required Discord Webhook format and posts it, something along the lines of https://aws.amazon.com/blogs/developer/receiving-amazon-sns-messages-in-php-2/.

Thanks again.
