### ISSUE TITLE
Tag new releases

### ISSUE THREAD

**Issue by mTrax-** [jammehcow/jenkins-discord#30]
Hi,

Last months changes have not been released to .hpi
Is it possible to have the .hpi for the latest changes ?
Moreover, when installed, the 1.1.0 version has this link : https://ci.jammehcow.co.nz/job/Discord%20Notifier/ which is not working anymore.

Thanks !

**Comment by jupjohn** [comment]
Cheers for that. I'll change that link, but you're going to have to wait until another update before I release a HPI file. You're welcome to build it yourself though.

**Comment by jupjohn** [comment]
See https://github.com/jammehcow/jenkins-discord/releases/tag/v1.3.0
