### ISSUE TITLE
Trouble with thumbnail URL and URL linking

### ISSUE THREAD

**Issue by azeier** [jammehcow/jenkins-discord#35]
The webhook generally works and editing the title does too. However:
- "Thumbnail url" sometimes works (I think I manged to have a thumbnail once out of 10 tries) but most of the time the field just resets to being empty on the next build.
- "URL linking" either doesn't work (i.e. stays checked butt no linking happens) or resets to unchecked on the next build.

The "Jenkins Location - Jenkins URL" is configured correctly. I don't see anything related in the system logs.

Using Jenkins 2.141 and jenkins-discord v1.3.0.

Running out of ideas for what to try. Any help would be much appreciated.

**Comment by KocproZ** [comment]
URL  linking turns itself off automatically if it doesn't detect Jenkins URL.
When it happens you should see this inside your job Console output:
`Your Jenkins URL is not set (or is set to localhost)! Disabling linking.`
Was the Jenkins URL set automatically? If yes please update it in some way (eg. change it to something else and back).

As for the thumbnail issue I'm still looking into it, but can't reproduce it yet.

**Comment by azeier** [comment]
I do see that output. I just tried setting the url to `google.com`, reenabling the setting and running the job, followed by setting it back to the previous url and doing the same. Got the same `Your Jenkins URL is not set (or is set to localhost)! Disabling linking.` both times.

Jenkins is configured to require login without any access for anonymous users, could that be an issue?

**Comment by KocproZ** [comment]
Ok, another idea.
Can you please install [this](https://jenkins.b.snet.ovh/job/Discord-notifier/job/%252335-fix/1/artifact/target/jenkins-discord.hpi) version of the plugin, run the job and find in the Console output something like this:
```
global config1: null: false, urlNull: false
global config: null: false, urlNull: false
```
Then post it here.

And configuration requiring login shouldn't be an issue.

**Comment by azeier** [comment]
Sorry for the delay, here's the output:
```
global config1: null: false, urlNull: true
global config: null: false, urlNull: false
```

**Comment by azeier** [comment]
It looks like the URL linking is now working 👍
