### ISSUE TITLE
Confusing 'unstable' parameter

### ISSUE THREAD

**Issue by HLXEasy** [jammehcow/jenkins-discord#37]
Hi,

haven't tested explicitly right now but following the docu, this is very confusing:

```
unstable
    True makes the left-hand side of the embed green (Only when successful: true).
```

If a build is unstable (unstable == true), it must not be green but yellow!

**Comment by HLXEasy** [comment]
OK, tested it to be sure and it seems to be just a c&p error on the documentation. Settings unstable to true makes the notification bar yellow. :-)

**Comment by KocproZ** [comment]
I wanted to make this something like `status: "UNSTABLE"`, but that would break compatibility and force people to edit their Jenkinsfiles, so I kept `successful` and added `unstable` boolean.
So for this to work i added following rules:
`success: false` equals to build status FAILURE, `unstable` is ommited
`success: true, unstable: true` equals to build status UNSTABLE,
`success: true, unstable: false` equals to build status SUCCESS

Now I see it might be confusing to use and I am open to suggestions.
(Would something like optional value `status: "UNSTABLE/SUCCESS/FAILURE/ABORTED?"` be better?)

**Comment by lf-jeremy** [comment]
An enum of named `status` values like `UNSTABLE|SUCCESS|FAILURE|ABORTED` is much more explicit (and more flexible) than a boolean `success` with a modifier flag. Besides the addition of `ABORTED`, It also adds the possibility for a `PAUSED` value.

**Comment by KocproZ** [comment]
OK, If someone wants to test this [here](https://jenkins.b.snet.ovh/job/Discord-notifier/job/enum_status/lastSuccessfulBuild/artifact/target/jenkins-discord.hpi) is a version of the plugin with `result` enum that takes 4 values: `SUCCESS|UNSTABLE|FAILURE|ABORTED` (`successful` and `unstable` still work, but `result` overwrites them). I can add different values, but I don't know it they are needed.

**Comment by HLXEasy** [comment]
Works like a charm! Time for a new release. 💯
