### ISSUE TITLE
Too big embeds payload

### ISSUE THREAD

**Issue by Dahlgren** [jammehcow/jenkins-discord#4]
If the builds has quite a few artifacts the webhook request silently fails without any output in neither the build log or the Jenkins logger. One possible solution is to add a link to the artifacts page instead. That's our temporary solution at least :)

Discord returns a 400 BAD REQUEST and the following payload:

````JavaScript
{
    "embeds": [
        "0"
    ]
}
````

Thanks for a great plugin!

**Comment by jupjohn** [comment]
Thanks for letting me know and apologies for my absence.

I assume it's sending a payload more than 2000 characters so I'll do a check after artifacts and changes to make sure they don't push the limit. If only Discord sent back a proper error response.

EDIT: Max size is 2048 characters for an embed description.

**Comment by jupjohn** [comment]
Supposedly fixed in the most recent commit.
