### ISSUE TITLE
Feature Request: For Multi-configuration projects, show build name AND configuration name

### ISSUE THREAD

**Issue by melt7777** [jammehcow/jenkins-discord#41]
My name is melt7777 and I work with the PiMP OS Dev Team. We have filed this issue based on our testing. Thank you very much for your work toward our mutual goal of making easy and effective tools for jenkins. We are bringing this feature request to light because we believe it will be a good improvement to this software and we were unable to figure out how to do it, so we need your help.

We use many "Multi-Configuration Projects" in Jenkins to build a project across several production versions of our product based on labels of the nodes. For these projects, when jenkins-discord posts the notification to our discord channel, it shows up as the label but without the build name. We would like to add multi-configuration handling support or options such that, we can see the build name and the label. Thankfully, you did implement some new features in 1.4.1 that we can try to use to alleviate this (Advanced -> Title) However, we believe that this should not be an override but a default behavior. Also, this forces us to choose between build name and the label of the configuration.

Example screenshot, showing first, the label version, and then the specified titles: 

![image](https://user-images.githubusercontent.com/4382542/48133427-bcfb6880-e264-11e8-89ba-67b075a2c4e0.png)

Thank you very much for considering this improvement in your development and again great work on a very useful plugin!

~ melt7777
getpimp.org | miner.farm

**Comment by KocproZ** [comment]
Ok, i made this:
![image](https://user-images.githubusercontent.com/8616451/48266650-44e19e00-e430-11e8-9ad9-ff3a818e808a.png)
If this is what you had in mind you can download it [here](https://ci.jenkins.io/job/Plugins/job/discord-notifier-plugin/job/matrixConfiguration/2/artifact/target/discord-notifier.hpi).

**Comment by melt7777** [comment]
I did install that build but it is not providing the output like your example: I tried with and without titles and with various configurations. Updated Jenkins to latest, Double checked uninstalled and reinstalled your build and turned the version display back on.  It is still showing the MC as before. Please advise?

![image](https://user-images.githubusercontent.com/4382542/48313976-1fb87100-e591-11e8-83ed-377ade72f947.png)

![image](https://user-images.githubusercontent.com/4382542/48314044-f3512480-e591-11e8-91d8-63b61d0e3301.png)

**Comment by KocproZ** [comment]
Sorry for that, I misplaced some code.
[This new build](https://ci.jenkins.io/job/Plugins/job/discord-notifier-plugin/job/matrixConfiguration/3/artifact/target/discord-notifier.hpi) should work as expected.

**Comment by melt7777** [comment]
Excellent work! With or without a title specified, and with or without the version, it works as expected and as requested! Thank you so much for this. Please make it part of the main stream build, as it is a great improvement to an awesome plugin. Have a great evening!

![image](https://user-images.githubusercontent.com/4382542/48321969-28da2a00-e5f3-11e8-83bb-4f9a808ab649.png)
