### ISSUE TITLE
notifications on state change only

### ISSUE THREAD

**Issue by andyczerwonka** [jammehcow/jenkins-discord#8]
In order for Discord notifications to not become spam, it's be very useful if we were able to opt-into a state-change-only mode. The following screenshot is from the e-mail notification post-build action, and it does exactly that.

![selection_311](https://user-images.githubusercontent.com/138898/29754770-66cbf5b0-8b49-11e7-8d02-53951f896b0e.png)

The problem with getting notifications on every single build is that you really want to know when it breaks and when it's fixed again. I worry people will ignore the build notification because it just a successful build 99% of the time. Or at least it should be. :-)

**Comment by jupjohn** [comment]
It has been published as a feature in the latest build. I haven't tested it because I don't have the time nor the resources, but I'm fairly certain it works. The rest (from #6) are being implemented within the next few days. Leaving open until I test it or someone else gets in there before me.

**Comment by andyczerwonka** [comment]
This doesn't work. I turned on the "Only send on state change" and I get a message on every build. It'd be great if it could be, at the very least, tested lightly.

![selection_340](https://user-images.githubusercontent.com/138898/30595529-b3c4046c-9d0e-11e7-8860-c1bde3ec5875.png)

**Comment by andyczerwonka** [comment]
BTW, "Enable URL linking" seems to work. When I turn it off, I'm getting messages, so that's great. In my branch I used Markdown links in the description given they work. It's only the title that the Discord API rejects.

```java
String url = globalConfig.getUrl() + build.getUrl();
String descriptionPrefix = "**Build:** [#"
                + build.getId()
                + "]("
                + url
                + ")\n**Status:** ["
                + build.getResult().toString().toLowerCase()
                + "]("
                + url
                + ")";
```

**Comment by andyczerwonka** [comment]
I've issued a PR with a fix. https://github.com/jammehcow/jenkins-discord/pull/10
